###
GET http://localhost:5000/api/users

###

POST http://localhost:5000/api/users
Content-Type: application/json

{"vorname": "Jordan",  "nachname": "dilane",   "email": "probe@mail.de2",   "passwort": "super2",  "rolle": "Admin2"}

###
GET http://localhost:5000/api/users/testUsers

###
POST http://localhost:5000/api/users/testUsers
Content-Type: application/json

[
{"vorname": "iva",  "nachname": "müller",   "email": "gf12@mail.de2",   "passwort": "frtg546",  "rolle": "Student"},
{"vorname": "Jordan",  "nachname": "Überall",   "email": "test@mail.de2",   "passwort": "4587",  "rolle": "Student"},
{"vorname": "Adel",  "nachname": "Sari",   "email": "adelsari@mail.de",   "passwort": "King",  "rolle": "Student"},
{"vorname": "Johana",  "nachname": "Müller",   "email": "fjohanna@mail.de",   "passwort": "miau",  "rolle": "Superuser"},
{"vorname": "Yan",  "nachname": "brice",   "email": "mad@mail.de",   "passwort": "0123456",  "rolle": "Admin"}
]

###
GET http://localhost:5000/api/users/edit?ID=2

###
POST http://localhost:5000/api/users/edit
Content-Type: application/json

{"id":"1","vorname": "annabel",  "nachname": "schmidt",   "email": "annabel@mail.de",   "passwort": "ann01232",  "rolle": "Admin"}
###
GET http://localhost:5000/api/users/delete?ID=1

###
GET http://localhost:5000/api/users/sortVName

###
GET http://localhost:5000/api/users/sortName

###
GET http://localhost:5000/api/users/sortRolle

###
GET http://localhost:5000/api/users/sortID

###
GET http://localhost:5000/api/users/vnameFilter?wordpart=ld

###
GET http://localhost:5000/api/users/nameFilter?wordpart=en

###
GET http://localhost:5000/api/users/rolleFilter?wordpart=User

###
DELETE http://localhost:5000/api/users

###
