###
GET http://localhost:5000/api/users

###
POST http://localhost:5000/api/users
Content-Type: application/json

{"vorname": "test2",  "nachname": "einnachname2",   "email": "test@mail.de2",   "passwort": "supersicher2",  "rolle": "Admin2"}

###
GET http://localhost:5000/api/users/testUsers

###
GET http://localhost:5000/api/users/edit?ID=2

###
POST http://localhost:5000/api/users/edit
Content-Type: application/json

{"id":"2","vorname": "Hello",  "nachname": "Pencer",   "email": "spencer@mail.de",   "passwort": "supersicher2",  "rolle": "User"}
###
GET http://localhost:5000/api/users/delete?ID=1

###
DELETE http://localhost:5000/api/users