###
GET http://localhost:5000/api/users

###
POST http://localhost:5000/api/users
Content-Type: application/json

{"vorname": "test2",  "nachname": "einnachname2",   "email": "test@mail.de2",   "passwort": "supersicher2",  "rolle": "Admin2"}

###
GET http://localhost:5000/api/users/testUsers

###
GET http://localhost:5000/api/users/delete?ID=1

###
DELETE http://localhost:5000/api/users